### ISSUE TITLE
Help mee

### ISSUE THREAD

**Issue by cata0309** [tree-sitter/tree-sitter-cpp#10]
How to install this on windows 7 64x in Atom??

**Comment by maxbrunsfeld** [comment]
Atom ships with this package; you don't need to do anything to install it. You do need the most recent version of Atom, and for now you need to check the `Use Tree-sitter Parsers` checkbox in the settings view.

**Comment by maxbrunsfeld** [comment]
Also, in the future when you open issues on GitHub, please try to describe your problem clearly in the title. Don't use titles like "Help mee".

And before opening an issue, please read all information that's already available online, and give a short explanation in the issue description about what steps you tried, and why the existing information was not enough. It doesn't have to be long - just something like this:

> I found out <somewhere> that this library can be used in Atom. But when I open C++ files in Atom, I see <something>. I can't find any information on how to use Tree-sitter parsers in Atom.

**Comment by cata0309** [comment]
I don't know how to associate this to the built in Atom tree-sitter. How to install the tree-sitter-cpp ? This is not shiped with Atom editor and how to build a grammar, there are no instructions neither onhttps://tree-sitter.github.io/tree-sitter/ 
I want clear instructions, do this and do that
I hope you can help me please

**Comment by maxbrunsfeld** [comment]
> This is not shiped with Atom editor

Yes, it is. The Atom text editor includes this library.

**Comment by cata0309** [comment]
But the tree-sitter-cpp is not and I don't know how to install it, help me
