### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by cata0309** [tree-sitter/tree-sitter-cpp#11]
I don't know how to associate the tree-sitter-cpp to the built in Atom tree-sitter. How to install the tree-sitter-cpp ? This is not shiped with Atom editor and how to build a grammar, there are no instructions neither on https://tree-sitter.github.io/tree-sitter/
I want clear instructions, do this and do that
I hope you can help me please
Windows 7 64x bit

**Comment by maxbrunsfeld** [comment]
Atom includes this library already. You don't need to do anything to install it. You just need the most recent version of Atom, and for now you need to check the `Use Tree-sitter Parsers` checkbox in the settings view.

**Comment by cata0309** [comment]
But it is not working, the underlining and the highlighing of the local
variables

joi, 23 aug. 2018, 21:00 Max Brunsfeld <notifications@github.com> a scris:

**Comment by cata0309** [comment]
Guide me, how to create a grammar for cpp, some instructions

joi, 23 aug. 2018, 21:03 Mr. Reaper <catalinmarincia@gmail.com> a scris:

**Comment by cata0309** [comment]
But what do your package do instead of highlighting ? In the presentation
video were a lot of things, but not all are visible or existing in your
package

joi, 23 aug. 2018, 21:22 Max Brunsfeld <notifications@github.com> a scris:

**Comment by cata0309** [comment]
And why this package is not working ??
https://atom.io/packages/tree-sitter-syntax-visualizer

joi, 23 aug. 2018, 21:26 Mr. Reaper <catalinmarincia@gmail.com> a scris:
