### ISSUE TITLE
Doxygen highlighting

### ISSUE THREAD

**Issue by tom-anders** [tree-sitter/tree-sitter-cpp#116]
I used to do `set syntax=cpp.doxygen` in vim which would give me nice highlighting for doxygen documentation comments, but with Treesitter this doesn't work anymore. Would it be possible in theory to include highlighting rules for doxygen comments into tree-sitter-cpp?

**Comment by maxbrunsfeld** [comment]
I think we'd probably want to solve this by making a specific grammar just for Doxygen, and then parsing C++ comments using that grammar, via language *injection*. I'm not familiar with the details of how language injection works in Neovim, but I think there is support for it.

/cc @tjdevries @vigoux @theHamsta

**Comment by tjdevries** [comment]
Yeah, we have language injection, it's not too hard to add generally just via a query.

**Comment by tom-anders** [comment]
I just upgraded to neovim 0.5 stable and noticed that 

`set syntax=cpp.doxygen`

followed by 

`hi TSComment gui=NONE`

brings back correct doxygen highligting! I'm not sure if I just didn't noticed this before or if it was introduced by some change in neovim.

However, for some reason 
`set syntax=cpp.doxygen` in my `ftplugin/cpp.vim` does not work. Is this somehow overriden by Treesitter?

**Comment by theHamsta** [comment]
@tom-anders you want to use this option.

**Comment by tom-anders** [comment]
@theHamsta Ah perfect, thanks!

**Comment by tom-anders** [comment]
@maxbrunsfeld @tjdevries I guess we should leave this issue open though, because language injection would be an even better solution?

**Comment by theHamsta** [comment]
@tom-anders language injection is implemented by each editor. It is not an issue of Tree-Sitter itself. When there's a parser of doxygen it can be used by Neovim or Atom.

**Comment by tom-anders** [comment]
@theHamsta No you're right, there should be a separate parser for doxygen, since it could also be used by other languages (C, Java etc.). I have some time on my hands right now and could try to write a parser. I think [](https://tree-sitter.github.io/tree-sitter/) would be the best reference for getting started?

Maybe I can also use https://github.com/tree-sitter/tree-sitter-jsdoc as a reference.

**Comment by XVilka** [comment]
For anyone who will work on implementing it, please note that doxygen accepts not only `@param` but also `\param` syntax

**Comment by tan-wei** [comment]
Hmm. Any progress? It would be great if it is implemented.

**Comment by tan-wei** [comment]
OK, it is not planed. Sorry to here that. But many thanks.

**Comment by amaanq** [comment]
well it's not exactly a C++ issue, a doxygen parser is needed.

**Comment by tan-wei** [comment]
I agree with you. Just like tree-sitter-jsdoc and tree-sitter-luadoc, something like tree-sitter-doxygen is needed.

**Comment by amaanq** [comment]
I might as well make it

**Comment by tan-wei** [comment]
Wow, Great! @amaanq

**Comment by amaanq** [comment]
It's not perfect and contributions are welcome, but it's a solid start imo

It's mostly missing the markup stuff

https://github.com/amaanq/tree-sitter-doxygen

**Comment by tan-wei** [comment]
Great, I'll try your plugin. Thanks!
