### ISSUE TITLE
Support for __restrict__ keyword

### ISSUE THREAD

**Issue by reiver-dev** [tree-sitter/tree-sitter-cpp#117]
Please add support for `__restrict__` extension.
- restrict is not a valid C++ keyword, though many code-bases do `#define restrict __restrict__`
- ms extension `__restrict`  is currently supported
- gcc/clang `__restrict__` is not supported and thus results in type definition to be binary expression `T  * var` instead.

**Comment by reiver-dev** [comment]
Figured out the issue has to be solved at C grammar: tree-sitter/tree-sitter-c#71

**Comment by amaanq** [comment]
It's fixed now
