### ISSUE TITLE
Brace vs Paranthesis Initialization

### ISSUE THREAD

**Issue by nick-prat** [tree-sitter/tree-sitter-cpp#14]
Brace Initialization treats the class name as a `syntax--entity.syntax--name.syntax--type` while Parenthesis Initialization treats the class name as a `syntax--support.syntax--storage.syntax--function`, this causes them to be highlighted differently.

![class_highlight_ts_cpp](https://user-images.githubusercontent.com/19151224/45522385-b387df80-b790-11e8-97c0-dba912276071.png)
```
class ClassA {

};

ClassA a1 = ClassA();
ClassA a2 = ClassA{};
```

**Comment by maxbrunsfeld** [comment]
This is a tricky one. With a braced initializer, we can tell that `ClassA` is a class name. But with parenthesis initialization, we can't tell that it's a class as opposed to a function (at least not without making our syntax highlighting context-sensitive). We *could* give up on highlighting `ClassA{}` as a type just for consistency, but I'm reluctant.

**Comment by nick-prat** [comment]
I understand the issue, although I believe the best solution would be to drop the special highlighting for `ClassA{}`. `ClassA{}` does (almost) the exact same thing as `Class()` so it would make sense they are highlighted in the same way.

**Comment by amaanq** [comment]
Imo, a regex checking for Pascal-case identifiers is the way to go (and is how nvim-treesitter does it btw)
