### ISSUE TITLE
Is this plugin Repo. relate to the c++ standards?

### ISSUE THREAD

**Issue by nyngwang** [tree-sitter/tree-sitter-cpp#142]
I'm new to treesitter. I want to write code in c++20. I have already install nvim-treesitter(so I linked to here). Do I still need to install syntax highlighting plugin for C++20?

**Comment by jdrouhard** [comment]
nvim-treesitter provides you with syntax highlighting for neovim, which is powered by this treesitter parser. C++20 language features must be implemented here for it to highlight things correctly using nvim-treesitter.

Concepts will be in #138, spaceship operator is in #104, and other c++20 features have already been added (such as coroutines). If you see anything else missing, feel free to open a PR with the changes or a separate issue for the specific feature. I know there are still a few missing things from the c++20 standard (modules, consteval/constinit, designated initializers, template parameter lists on lambdas, conditional explicit).

**Comment by nyngwang** [comment]
@jdrouhard  IIRC the `constexpr` and some coroutine are missing. Sorry for my fuckingly bad memory, I will check this later and update the comment.

-- by a cat just desperately solved a neovim config bug

**Comment by jdrouhard** [comment]
`constexpr` and coroutines should work. If not, open a separate issue that shows and describes the problem.

**Comment by nyngwang** [comment]
@jdrouhard  Sorry, I meant `consteval`:

<img src="https://user-images.githubusercontent.com/24765272/149821887-f4d61bbe-41e6-4634-b7c1-87fae049e0d5.png" width="600">

**Comment by jdrouhard** [comment]
That is your language server diagnostic (probably clangd with the built-in LSP client). This is just the c++ parser for treesitter to power the syntax highlighting via the nvim-treesitter plugin, so that diagnostic is not related to this repo.

Update your nvim-treesitter plugin if you want the syntax highlighting for consteval to work. I implemented that last night.

**Comment by nyngwang** [comment]
@jdrouhard: What exactly should I update...? I'm using the official `nvim-lspconfig` if this is what you meant language server diagnostic.

**Comment by jdrouhard** [comment]
Yes, this repo has nothing to do with language servers. Please open an issue there if you are having trouble with LSP-specific things (like this).
