### ISSUE TITLE
error render in initialize-list

### ISSUE THREAD

**Issue by cathaysia** [tree-sitter/tree-sitter-cpp#143]
Something just like this:

![图片](https://user-images.githubusercontent.com/42114817/147866382-15df3314-4c4e-466f-846b-385206c5634b.png)

**Comment by jdrouhard** [comment]
Unfortunately this is because of the `Q_OBJECT` macro--it throws the parser off since it's not valid c++ by itself (it requires the preprocessor to change it to valid c++). There has been much discussion about this, but unfortunately it's not resolvable in treesitter.

**Comment by jdrouhard** [comment]
Dupe of #137 and #85.
