### ISSUE TITLE
Methods starting with capital letters are highlighted as constructors

### ISSUE THREAD

**Issue by mrmansano** [tree-sitter/tree-sitter-cpp#145]
Hi, first of all: thank you for the work on TS! 

Recently I've noticed that class methods that starts with a capital letter (uppercase) are being highlighted as constructors:
For example, in this case we have two methods in the class Test:

![image](https://user-images.githubusercontent.com/4893748/149560305-5a6bd398-9243-4a26-98c3-e10dcf0e0600.png)

The "reset" method, starting with lower case 'r' is highlighted as function:

![image](https://user-images.githubusercontent.com/4893748/149560533-02cd8a0a-7d55-4b8b-921a-2e066b9f83b4.png)

However, the "Set" method is highlighted as constructor:

![image](https://user-images.githubusercontent.com/4893748/149560588-de7da798-f9d7-41b9-b86b-f0289fa5f0bb.png)

Is this a bug? Or is it intended to be this way?

**Comment by jdrouhard** [comment]
This doesn't have anything to do with this c++ parser. It's the way the query is written in nvim-treesitter for the c++ language. I'd raise the question there.
