### ISSUE TITLE
Parameter lists inside parameter lists

### ISSUE THREAD

**Issue by FoamScience** [tree-sitter/tree-sitter-cpp#146]
I know how parsing macros can be extremely painful, but I would like to at least understand something like this:
```
    declareRunTimeSelectionTable
    (
        autoPtr,
        coupledSystem,
        phases,
        (                                                    // <-  Recursive parameter_list?
            const fvMesh& mesh,
            const wordList& phaseNames
        ),
        (mesh, phaseNames)                 // <- a nameless function declarator
    );
```
I've been trying to implement this without any success. Anyone has an idea on how can this be implemented?

**Comment by jdrouhard** [comment]
Is `declareRunTimeSelectionTable` a macro that tree sitter is parsing as a function call expression?

Unfortunately a parameter list isn't itself an expression. You could define a new macro (like `NESTED(...)`) that doesn't do anything but wrap the va args in parentheses, and then use that. Treesitter would parse those are function calls as well:

```cpp
#define NESTED(...) (__VA_ARGS__)

declareRuneTimeSelectionTable
(
    autoPtr,
    coupledSystem,
    phases,
    NESTED(
        const fvMesh& mesh,
        const wordList& phaseNames
    ),
    NESTED(mesh, phaseNames)
);
```

**Comment by FoamScience** [comment]
@jdrouhard Thanks for putting me on the right track! Instead of making changes to my code (Mostly, I don't have control over it), I would like the parser to not throw ERRORs/MISSINGs at me (Hence, somehow making 'NESTED' (which is a  type field in the tree) optional).

For me, it's fine if the macro gets parsed as a function call; all that matters is that it gets parses successfully.
I've started a PR #149 where I copied some rules from the c parser (and tweaked em a little) and added a new one with a low priority. All tests are passing, can you please take a look and see if you can spot any possible failure cases?

**Comment by FoamScience** [comment]
As suggested, I'm maintaining a separate fork to support non-compliant c++. Mainly targeting [OpenFOAM code](https://github.com/OpenFOAM/OpenFOAM-dev), If you're having similar issues; [FoamScience/tree-sitter-cpp](https://github.com/FoamScience/tree-sitter-cpp/) might help.
