### ISSUE TITLE
function template identifier fails to highlight

### ISSUE THREAD

**Issue by ville-h** [tree-sitter/tree-sitter-cpp#153]
In the following the `dynamic_array_new()` function template does not appear to get highlighted when I am using tree-sitter in emacs. I observed the `trees-sitter-debug-mode` and there appears to be some `ERROR` nodes in the output. I was told I should report such errors to this project possibly? Anyway I tried to produce somewhat-minimal valid c++ but perhaps bit nonsensical code snippet that still displays the issue:
```
namespace nn {
    using u32 = unsigned;


    struct dynamic_array {
        // changing to non-const makes highlighting work
        auto operator [](u32 i) const -> u32 const&;

        // altering these makes highlighting work
        u32* buffer = nullptr;
        u32 buffer_size = 0;
        u32 size = 0;
    };


    template<typename T> // removing this makes highlighting work
    // function name does not get highlighted
    auto dynamic_array_new() -> void {
    }
}
```

**Comment by jdrouhard** [comment]
Thanks for the report.

This is a "simple fix" with two or three possible resolutions, but I want to get @maxbrunsfeld's opinion on which way we should go.

@maxbrunsfeld  - we can either "copy/paste" the guts of the `$.type_descriptor` rule into `$.trailing_return_type`, or we can simply change the `$.trailing_return_type` rule to use `$.type_descriptor` directly.

If we use `$.type_descriptor` directly, we introduce a new named node under each `trailing_return_type` that will always be there and always be a single node, which is usually the justification for making the node hidden so it gets "expanded" into the parent node. If we copy/paste, it keeps the existing tests/parsed trees the same as they are now, but we if we ever want to change or expand on `type_descriptor`, we'd have to remember to go update `trailing_return_type` as well.

The other option is to consider making a hidden `$._type_descriptor_internal` node with the implementation that can be used by both `type_descriptor` and `trailing_return_type` but this would require a change to the C grammar. This actually feels the cleanest to me, but I'd like your thoughts.

Note, we would have to make `type_descriptor` have right precedence if we use it directly in the `trailing_return_type` rule (either with the internal hidden rule or the named rule).

```javascript

    trailing_return_type: $ => prec.right(seq(
      '->',
      repeat($.type_qualifier),
      field('type', $._type_specifier),
      repeat($.type_qualifier),
      field('declarator', optional($._abstract_declarator))
    )),
```

or

```javascript
    type_descriptor: ($, original) => prec.right(original), // this might be a good change for the C grammar anyway
    trailing_return_type: $ => seq('->', $.type_descriptor), // or an internal hidden implementation if we go that way
```

**Comment by maxbrunsfeld** [comment]
I like your second solution: reusing the `type_descriptor`. I don't think it needs to be hidden. I'm fine with overriding `type_descriptor` to give it a rightward precedence in C++. I'm also ok w/ changing the C grammar, if you think that makes more sense.

**Comment by jdrouhard** [comment]
Fixed by https://github.com/tree-sitter/tree-sitter-cpp/commit/a832195eb3685a279856bb480ce19cff19554b6d

**Comment by maxbrunsfeld** [comment]
Thanks @jdrouhard, nice work on the fix.

**Comment by jdrouhard** [comment]
@maxbrunsfeld sure thing. I went ahead and put the right precedence for type_descriptor here, but it probably does make sense to add that to the c grammar even though there aren't currently any conflicts there.
