### ISSUE TITLE
Abseil and other macros

### ISSUE THREAD

**Issue by defr0std** [tree-sitter/tree-sitter-cpp#154]
Hi,

We are using a few libraries with C++ macros, which cause some parsing troubles with treesitter.

Here are a few examples.
1. [Abseil flags library](https://abseil.io/docs/cpp/guides/flags):
Example:
```c++
ABSL_FLAG(int, a);
```

The current grammar attempts to parse it as a function declarator, which causes an error:
```lisp
    (translation_unit
      (ERROR
        (function_declarator
          (identifier)
          (parameter_list
            (parameter_declaration
              (primitive_type))
            (parameter_declaration
              (type_identifier)))))
      (expression_statement))
```

2. [status_macros.h](https://github.com/google/mediapipe/blob/master/mediapipe/framework/deps/status_macros.h):

A similar problem here:
```c++
ASSIGN_OR_RETURN(int a, b);
```
Also attempted to be parsed as function declarator:
```lisp
    (translation_unit
      (ERROR
        (function_declarator
          (identifier)
          (parameter_list
            (parameter_declaration
              (primitive_type)
              (identifier))
            (parameter_declaration
              (type_identifier)))))
      (expression_statement))
```

I assume the common problem is that these constructs do look like function declarations, e.g. `int main(int,int)`, but the return type is missing.

Do you have any suggestions on how to address such constructs without duplicating much of the declaration structures?

**Comment by amaanq** [comment]
if you want to use/write a grammar based on this, the sizeof/offsetof expressions take types for arguments, and that can be applied here.
