### ISSUE TITLE
Release and tag a new version

### ISSUE THREAD

**Issue by jirutka** [tree-sitter/tree-sitter-cpp#155]
Can you please release a new version? The latest one (v0.20.0) doesn’t work with modern nvim-treesitter.

I’m maintainer of the [tree-sitter-cpp](https://pkgs.alpinelinux.org/packages?name=tree-sitter-cpp) package in Alpine Linux and I had to update the package to the latest revision in the master branch, instead of using the tagged release, which is not optimal.

**Comment by jdrouhard** [comment]
Ping @maxbrunsfeld

**Comment by jirutka** [comment]
ping @maxbrunsfeld

**Comment by XVilka** [comment]
Once the CI regression is fixed, would be nice to have a new tag for this, @aryx

**Comment by amaanq** [comment]
there's a new one
