### ISSUE TITLE
operator overload fails to highlight

### ISSUE THREAD

**Issue by ville-h** [tree-sitter/tree-sitter-cpp#157]
An operator overload fails to highlight the function name.
```
struct aa {
};


// operator overload
auto operator +(aa const&, aa const&) -> aa {
    return {};
}


auto main() -> int {
    return 0;
}
```
I would have expected the "operator +" part to be highlighted same as other non-member functions. I was able to get a successful hack by adding:
```
(function_declarator (operator_name) @function)
```
in emacs. It highlights the "operator +" part. Also something funny is going on with the word "overload" highlight in the comment.

**Comment by amaanq** [comment]
same as your other issue
