### ISSUE TITLE
keywords in comments cause incorrect highlighting

### ISSUE THREAD

**Issue by ville-h** [tree-sitter/tree-sitter-cpp#166]
The following keywords cause the word "highlights" after them to be highlighted incorrectly
```
// namespace highlights incorrectly
// new highlights incorrectly
// operator highlights incorrectly


auto main() -> int {
    return 0;
}
```

**Comment by jdrouhard** [comment]
This doesn't have anything to do with the parser.

You'll need to raise this issue with the maintainer of your editor's tree/sitter queries and semantic highlighting. It's probably doing an extra pass looking for keywords.
