### ISSUE TITLE
Support init-statements in for loops

### ISSUE THREAD

**Issue by ibldzn** [tree-sitter/tree-sitter-cpp#167]
it's expecting a boolean expression after the init-statement and thus it says that the last 2 for loops are not a valid statement

reproducible code (requires C++20):
```c++
#include <array>

int main()
{
    constexpr std::array arr { 1, 2, 3, 4, 5 };
    for (auto v : arr) { }
    for (std::size_t i = 0; const auto v : arr) { }
    for (std::size_t i = 0; const auto v : arr) { }
}
```

the syntax highlighting in line 7 and anything below is kind of broken because of this
![Screenshot](https://i.imgur.com/sujTat6.png)

**Comment by jdrouhard** [comment]
Fixed by 818a564
