### ISSUE TITLE
CI is not working

### ISSUE THREAD

**Issue by mliszcz** [tree-sitter/tree-sitter-cpp#177]
Since the release of tree-sitter-cli 0.20.7 our CI builds are failing.
A breaking change was introduced in: https://github.com/tree-sitter/tree-sitter/commit/149bae57747c0ecdf1709bd0f943a3bdbb43b790

tree-sitter-cli now instantiates an `URL` object which is only available starting with node v9.8.0 (we are using v8.17.0):
https://stackoverflow.com/questions/52566578/url-is-not-defined-in-node-js/52566656#52566656
https://www.nehemiahj.com/2021/06/referenceerror-url-is-not-defined.html

**Comment by jdrouhard** [comment]
Fixed in 9a877b6180cfc419622363fa56205505565b4a4f
