### ISSUE TITLE
Why disabled optimize?

### ISSUE THREAD

**Issue by timxx** [tree-sitter/tree-sitter-cpp#182]
Inside parser.c, it contains the following codes:
```C
#ifdef _MSC_VER
#pragma optimize("", off)
#elif defined(__clang__)
#pragma clang optimize off
#elif defined(__GNUC__)
#pragma GCC optimize ("O0")
#endif
```
It  introduced in [https://github.com/tree-sitter/tree-sitter-cpp/commit/565244b6f6d7ed371537d246003ac585b61c53f0](https://github.com/tree-sitter/tree-sitter-cpp/commit/565244b6f6d7ed371537d246003ac585b61c53f0), with no further explain.

I don't known why disabled optimize, from my point, this can be slow down the performance in release build.

**Comment by jdrouhard** [comment]
It's because of https://github.com/tree-sitter/tree-sitter/commit/4badd7cc400f61c74ad42aafe53e275c91742c54

But @maxbrunsfeld will have to comment here. I agree that enabling optimizations probably would help the performance of this lexer/parser pretty substantially.

**Comment by amaanq** [comment]
FWIW I don't think it really does - I tried using an optimized version to parse the entire linux kernel and shaved like 10 seconds off out of a ~4 min parse - you can see try out my "optimize" flag in this branch: https://github.com/amaanq/tree-sitter/tree/optimize
