### ISSUE TITLE
Math Operators

### ISSUE THREAD

**Issue by nick-prat** [tree-sitter/tree-sitter-cpp#19]
The only Math operator that is properly highlighted is the *

![math_operators2](https://user-images.githubusercontent.com/19151224/45533646-6de60980-b7c6-11e8-811e-6ac23ef0c8de.png)

**Comment by Ben3eeE** [comment]
Thanks for the report!

This was fixed in https://github.com/atom/language-c/pull/300 that shipped in Atom 1.32.1. We are working on fixing more operators and scopes in https://github.com/atom/language-c/pull/303
