### ISSUE TITLE
Can Tree Sitter parse MSVC developed source?

### ISSUE THREAD

**Issue by VenoVeno** [tree-sitter/tree-sitter-cpp#194]
The grammar written is purely for CPP Source. Whether the grammar abides to only GNU standard or it also supports MSVC source?
Visual Studio Compiler is a wrapper written on C++ compiler, which have a quite different syntax.

Thanks.

**Comment by jdrouhard** [comment]
This grammar is for standard c++ only. You are welcome to fork this repo and create another parser for the extensions supported by MSVC.

**Comment by VenoVeno** [comment]
But i also has some MS keyword support? `ms_call_modifier`, `ms_declspec_modifier`, `ms_based_modifier`, `ms_restrict_modifier`, `ms_unsigned_ptr_modifier`, `ms_signed_ptr_modifier`, `ms_unaligned_ptr_modifier`, `ms_pointer_modifier`?

**Comment by VenoVeno** [comment]
@jdrouhard Any update on this?
