### ISSUE TITLE
function_declarator node in unexpected place

### ISSUE THREAD

**Issue by Jendker** [tree-sitter/tree-sitter-cpp#196]
Moving the issue from https://github.com/nvim-treesitter/nvim-treesitter/issues/4552.

If I have following line:
```
auto object_plane_pose(Eigen::Isometry3d::Identity());
```

A `function_declarator` node is marked between columns 5 and 53, what is not expected. We have a call as one of the arguments, so it cannot be a function declaration. I am not sure how to adjust the syntax parsing to fix that. Could someone have a look?

![Screenshot from 2023-03-24 12-14-15](https://user-images.githubusercontent.com/14967831/227529192-7b3b1f8e-8f70-41bf-bb4b-3bd820815917.png)

**Comment by jdrouhard** [comment]
This is called [most vexing parse](https://en.m.wikipedia.org/wiki/Most_vexing_parse). It's impossible to determine the actual semantic meaning of this expression without a compiler's assistance. A language server (clangd) with semantic token highlighting enabled in your editor would likely help.
