### ISSUE TITLE
[FEATURE] Export constants for symbols in C api

### ISSUE THREAD

**Issue by Sanek1710** [tree-sitter/tree-sitter-cpp#199]
Is it possible to add enum or some way to define int symbol constants on the level of API?
so that user could compare node type like so:
```cpp
    if (ts_node_symbol(node) == ts_symbols::if_statement) {
      // do something cool
    }
```
(even macro definitions would be cool)
I dont really know for sure, but im guessing that it shouldnt be too hard to add (especially if whole header is (probably) generated from grammar)

and parser.c already has something like that:
```cpp
enum {
  sym_if_statement = 267,
  sym_switch_statement = 268,
  sym_case_statement = 269,
  sym_while_statement = 270,
  ...
}
static const char * const ts_symbol_names[] = {
  [sym_if_statement] = "if_statement",
  [sym_switch_statement] = "switch_statement",
  [sym_case_statement] = "case_statement",
  [sym_while_statement] = "while_statement",
  ...
}
```

but its anonymous and static :(

**motivation:**
- defining enum like so in user code might be pretty hard for multiple language parsing
- strlen works, but might be slow for large code bases

Pretty please,
Cheers!

**Comment by amaanq** [comment]
Hmm, it is now no longer an anonymous enum - does that work for you?
