### ISSUE TITLE
Variadic Templates

### ISSUE THREAD

**Issue by nick-prat** [tree-sitter/tree-sitter-cpp#20]
Syntax Highlighting for Variadic Template functions causes some strange errors.

![variadic_templates](https://user-images.githubusercontent.com/19151224/46776622-6557f480-ccda-11e8-9d23-37cfa6c8d93e.png)

1. The type name `Ts` in the func2 declaration isn't highlighted
2. The variable name `args` in the func2 declaration isn't highlighted
3. It causes the `void` in the func3 declaration to be not highlighted
4. Error 2 only happens if the `&&` symbol is used
5. Error 3 only occurs if there is a `;` in the body of `func2` and they are in the same class declaration

**Comment by Ben3eeE** [comment]
For easy testing:

```cpp
template<class T>
class TT {
    template<typename... Ts>
    void func2(Ts&&... args) {
      func3(nullptr);
    }

    void func3(T* ptr) {
      
    }
};
```
