### ISSUE TITLE
Field is captured as a 'variable'

### ISSUE THREAD

**Issue by rickboks** [tree-sitter/tree-sitter-cpp#200]
Please see the below minimal example. The declaration of `myField` is correctly captured as a `property` and `field`, but when used inside of the definition of `myFun`, it is captured as a `variable(95)`. See also the below screenshots inside of NeoVim with the output of `:TSCaptureUnderCursor`, which shows the captures of the symbol under the cursor. When renaming `myField` to `m_myField`, the behaviour is correct.
```
class Test {
	public:
		void myFun();
	private:
		int myField = 0;
};

void Test::myFun(){
	myField += 1;
}
```
![image](https://user-images.githubusercontent.com/27772913/231410963-68c973db-cd13-42e7-a97e-dd6f601eb89b.png)
![image](https://user-images.githubusercontent.com/27772913/231411076-1cb9b697-4649-45ef-a7c2-e8a858492bb5.png)

**Comment by jdrouhard** [comment]
Parser can't know this without semantic analysis. Your best bet is to use LSP and get clangd's semantic tokens going. `m_*` is just a nvim-treesitter thing where it matches variables with those prefixes. It's not 100% and is pure guesswork based on the coding style used.
