### ISSUE TITLE
Use `Comment` for regions obviously disabled by the preprocessor.

### ISSUE THREAD

**Issue by no-more-secrets** [tree-sitter/tree-sitter-cpp#205]
One of clangd's semantic highlighting features that tree-sitter-cpp does not seem to have is that it will detect when a region of code is disabled by the preprocessor and assign the `Comment` highlight group to it.  E.g.:

```c++
int x = 0;  // highlighted normally.

#if 0
// This whole block will be colored like a comment.
int y = 0;
#endif

#if 1
// This block is highlighted normally.
int y = 0;
#endif
```

clangd, since it is compiling the code, can of course evaluate an arbitrary preprocessor expression in the `#if` clause, which I assume tree-sitter cannot do, but it could detect simple obvious cases, such as `#if 0`, which is sometimes used as an idiom for disabling some block of code e.g. during testing.

Actually, github's syntax highlighting seems to do this to some extent (see above), though the disabled text seems to be black instead of the grey comment color.

**Comment by jdrouhard** [comment]
See #144 and https://github.com/nvim-treesitter/nvim-treesitter/issues/1632
