### ISSUE TITLE
:bug: misidentified structure variable definition

### ISSUE THREAD

**Issue by cyw3** [tree-sitter/tree-sitter-cpp#207]
The following is a  query demo to capture struct's name:
```
(struct_specifier
  name: (type_identifier) @target_object
)
```

here is a cpp demo code:
```cpp
struct Student update_time;
```

expected:
- It is recognized that this is a line of code that defines a variable of type `struct Student` `update_time`.
- And can not be recognized as a struct definition `Student`.

bug:
- recognized as a struct definition `Student` and the query capture the `Student`.

**Comment by amaanq** [comment]
I don't get your problem, but this is not a bug
