### ISSUE TITLE
Fold expressions are not parsed explicitly

### ISSUE THREAD

**Issue by thomasjo** [tree-sitter/tree-sitter-cpp#21]
Fold expressions, which were introduced in C++17, are currently not explicitly parsed. It doesn't seem like there any scenarios that produces any parser errors though, so this can probably be considered a low-priority enhancement. However, since these expressions are not parsed correctly, it's currently not possible to target specific tokens, e.g. the ellipsis (`...`).

Full details on fold expressions can be found at https://en.cppreference.com/w/cpp/language/fold

Below are some examples of valid fold expressions, stolen from cppreference.com, which might be useful when attempting to resolve this issue.

``` cpp
template<typename... Args>
bool all(Args... args) { return (... && args); }
```

``` cpp
template<typename ...Args>
void printer(Args&&... args) {
    (std::cout << ... << args) << '\n';
}
```

``` cpp
template<typename T, typename... Args>
void push_back_vec(std::vector<T>& v, Args&&... args)
{
    static_assert((std::is_constructible_v<T, Args&> && ...));
    (v.push_back(args), ...);
}
```

``` cpp
// compile-time endianness swap based on http://stackoverflow.com/a/36937049 
template<class T, std::size_t... N>
constexpr T bswap_impl(T i, std::index_sequence<N...>) {
  return (((i >> N*CHAR_BIT & std::uint8_t(-1)) << (sizeof(T)-1-N)*CHAR_BIT) | ...);
}

template<class T, class U = std::make_unsigned_t<T>>
constexpr U bswap(T i) {
  return bswap_impl<U>(i, std::make_index_sequence<sizeof(T)>{});
}
```

**Comment by jdrouhard** [comment]
Fixed by #151
