### ISSUE TITLE
Code folding not working properly with functions defined by macros.

### ISSUE THREAD

**Issue by no-more-secrets** [tree-sitter/tree-sitter-cpp#211]
When using the popular Catch2 C++ unit testing framework, we have test cases like so:
```cpp
TEST_CASE( "description" ) {
  // test code.
}
```
However, tree-sitter-cpp (I'm using it with Neovim) does not know how to fold those properly, instead folders the outer namespace.  Is this something that can be fixed?

**Comment by amaanq** [comment]
Belongs in nvim-treesitter
