### ISSUE TITLE
Dependent template template arguments

### ISSUE THREAD

**Issue by elbeno** [tree-sitter/tree-sitter-cpp#223]
What to do about things like the following?

```cpp
template <typename T>
using X = A<T::template U>;
```
or
```cpp
template <typename... Ts>
using X = A<Ts::template U...>;
```

Both of these constructions are currently unsupported because dependent template arguments are assumed to be either types or NTTPs, not templates.

I've tried massaging  things around `qualified_type_identifier` (https://github.com/elbeno/tree-sitter-cpp/commit/729085b7a0d998c653a7a5212dcb0f0a03ac0ae6) which gives a hacky solution to the first of these. But it feels like a more proper solution could be found by rewriting the various `qualified_identifier` rules perhaps? They work recursively at the moment which means a potentially deep tree with nested scopes... perhaps a `repeat` rule would handle it better.

**Comment by amaanq** [comment]
Interesting - what about something like this?

```diff
diff --git a/grammar.js b/grammar.js
index 5503014..de2d303 100644
--- a/grammar.js
+++ b/grammar.js
@@ -1169,7 +1169,7 @@ module.exports = grammar(C, {
         alias($.dependent_identifier, $.dependent_name),
         $.qualified_identifier,
         $.template_function,
-        $.identifier,
+        seq(optional('template'), $.identifier),
         $.operator_name,
         $.destructor_name,
         $.pointer_type_declarator,
```
