### ISSUE TITLE
number (integer/float) literals

### ISSUE THREAD

**Issue by elbeno** [tree-sitter/tree-sitter-cpp#224]
tree-sitter-cpp inherits the `number_literal` rule from tree-sitter-c. There are a few problems with it.

(besides #108, which is just an easy fix)

Suffxes differ between the languages:
- C has the _bit-precise-int-suffix_ `wb`,  C++ doesn't
- C++ has the _size-suffix_ `z`, C doesn't
- C has decimal (?) float suffixes (`dd` etc) which aren't in C++
- C++ has sized float (`f16` etc) and brainfloat suffixes (`bf16`) which aren't in C

There are also some oddities within the `number_literal` rule itself. It is pretty lenient - I am not sure if this is a design decision for tree-sitter or not: should it accept things that a compiler will reject, to be lenient in parsing and minimize error nodes? Or should it be as close to the compiler as possible, so that editors can use it to identify errors and mark them?

Here are some erroneous literals it currently accepts (but compilers don't):
```cpp
0xf.1; // hex float literal without exponent part
0x0xa; // double hex prefix
0b0xa; // mixed prefixes
0b23;  // binary literal with decimal digits (or octal literal with an invalid digit)
42fluff; // invalid suffix
0.1p1; // hex exponent on non-hex fractional part
0x1pa; // hex digits in exponent
09;    // octal literal with digit out of range
```

Should we have a very lenient, union-of-possibilities rule for both languages, or should we fit the rules to the languages closely? Either way I think changes are needed, and probably not too difficult. Happy to help...

**Comment by amaanq** [comment]
I think it's better to be clear about which is which - I don't mind just rewriting the number/float rule for this
