### ISSUE TITLE
'nullptr' should be a @constant.builtin

### ISSUE THREAD

**Issue by tajtiattila** [tree-sitter/tree-sitter-cpp#229]
The cpp parser recognises `NULL` as `@constant.builtin` but `nullptr` is just a `@constant`.

I think `nullptr` should be a `@constant.builtin` too, because it is a C++ keyword: see [cppreference](https://en.cppreference.com/w/cpp/language/nullptr).

**Comment by tajtiattila** [comment]
For the record, in Neovim it is easy to fix with a user highlight configuration file `~/.config/nvim/queries/cpp/highlights.scm` with:

`(nullptr) @constant.builtin`

**Comment by aryx** [comment]
Unrelated but I seem to have problem contacting you @amaanq but did you see the email I sent you to 
amaanq12@gmail.com?
Is this still your valid email current address?

**Comment by amaanq** [comment]
Yep that's still my email - I thought I hadn't gotten anything, but I double checked and got your message, sorry about that
