### ISSUE TITLE
Weird behaviour with Structs

### ISSUE THREAD

**Issue by Aerijo** [tree-sitter/tree-sitter-cpp#23]
I feel the following is an issue because the full code compiles, which indicates it is a valid construction. I don't know much about structs in C++ though.

Anyway, the following is handled strangely (can see easier in Atom).

```
struct Scanner {

  vector<CategoryDescription> category_descriptions = {
    {FOO, FOO, FOO},
    {FOO, FOO, FOO}
  };

  map<string, TokenType> tokens = {
    {"(", BEGIN_INLINE_MATH},
    {")", END_INLINE_MATH},
  };

  map<char, Category> catcodes = {
    {'\\',   ESCAPE_CATEGORY},
    {'{',    BEGIN_CATEGORY}
  };

};
```

The first item is scoped differently to the others, and reordering them or adding fields above does not affect this (whatever the first is is still scoped differently).

It also folds incorrectly; folding line 1 folds up until the semicolon of the vector, when it should be folding the entire struct.

**Comment by thomasjo** [comment]
It's not related to structs. The problem is that [list initialization](https://en.cppreference.com/w/cpp/language/list_initialization) is not currently supported by the grammar.

**Comment by thomasjo** [comment]
Examples of various forms of list initialization, shamelessly borrowed from cppreference.com;

``` cpp
struct Foo {
    std::vector<int> mem = {1,2,3}; // list-initialization of a non-static member
    std::vector<int> mem2;
    Foo() : mem2{-1, -2, -3} {} // list-initialization of a member in constructor
};
 
std::pair<std::string, std::string> f(std::pair<std::string, std::string> p)
{
    return {p.second, p.first}; // list-initialization in return statement
}
 
int main()
{
    int n0{};     // value-initialization (to zero)
    int n1{1};    // direct-list-initialization
    std::string s1{'a', 'b', 'c', 'd'}; // initializer-list constructor call
    std::string s2{s1, 2, 2};           // regular constructor call
    std::string s3{0x61, 'a'}; // initializer-list ctor is preferred to (int, char)
 
    int n2 = {1}; // copy-list-initialization
    double d = double{1.2}; // list-initialization of a temporary, then copy-init
 
    std::map<int, std::string> m = { // nested list-initialization
           {1, "a"},
           {2, {'a', 'b', 'c'} },
           {3, s1}
    };
 
    std::cout << f({"hello", "world"}).first // list-initialization in function call
              << '\n';
 
    const int (&ar)[2] = {1,2};
}
```

**Comment by thomasjo** [comment]
Yeah, you're totally right! Just tested the examples I shared, and everything works fine except the struct with data member initialization. Sorry about the confusion, @Aerijo and @maxbrunsfeld 🙇

**Comment by maxbrunsfeld** [comment]
Fixed on Atom master! I hate to see Tree-sitter failing you *while* you're working on a Tree-sitter parser (guessing from your example). Thanks for raising this!
