### ISSUE TITLE
namespaces not indenting

### ISSUE THREAD

**Issue by MoolsDogTwo** [tree-sitter/tree-sitter-cpp#234]
Normally when writing a namespace, I expect it to look like this
```
namespace a
{
    void b()
    {
        std::cout << "Test 123.\n";
    }
}
```
But instead, indentation ends up not working at all.
```
namespace a
{
void b()
    {
    std::cout << "Test 123.\n";
}
}
```

**Comment by amaanq** [comment]
belongs in whatever tool is configuring indentation for you, this is the parser repo.

**Comment by MoolsDogTwo** [comment]
As far as I know, I loaded up LazyVim and tried the namespace thingy and for some reason broke after I installed this parser. Hmm, I'll look into it a bit.

**Comment by amaanq** [comment]
again, that doesn't belong here, that belongs in nvim-treesitter - this is just the parser.

**Comment by MoolsDogTwo** [comment]
Ok I disabled indent in tree-sitter and now it finally works. I thought this type of stuff was language dependent lol.

**Comment by amaanq** [comment]
It is but again this is not the repo for it, it's nvim-treesitter.
