### ISSUE TITLE
bug: Invalid capture @scope

### ISSUE THREAD

**Issue by tex** [tree-sitter/tree-sitter-cpp#235]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter-0.20.10

### Describe the bug

I am trying to use the new tags.scm in my Rust application and I am getting this error:

```
Invalid capture @scope. Expected one of: @definition.*, @reference.*, @doc, @name, @local.(scope|definition|reference).
```

```
tree-sitter = "0.20.10"
tree-sitter-tags = "0.20.2"
tree-sitter-cpp = "0.20.3"
```

### Steps To Reproduce/Bad Parse Tree

Use it in TagsConfiguration::new()

### Expected Behavior/Parse Tree

No error.

**Comment by amaanq** [comment]
Thanks, fixed on master
