### ISSUE TITLE
bug:  ERROR on `parameter_list`

### ISSUE THREAD

**Issue by jerry4718** [tree-sitter/tree-sitter-cpp#236]
### Did you check existing issues?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.20.3

### Describe the bug

An ERROR occurs when using both `abstract_reference_declarator` and `optional_parameter_declaration` simultaneously in `parameter_list`.
like ```void foo(Bar& = defaultBar);```

### Steps To Reproduce/Bad Parse Tree

nop

### Expected Behavior/Parse Tree

>optional_parameter_declaration
>> type: type_identifier
>> declarator: abstract_reference_declarator
>>> &

>> default_value: identifier

### Repro

```cpp
// Example code that causes the issue
class Foo {
public:
    void foo(Bar& = defaultBar);
}
```

**Comment by amaanq** [comment]
thanks for the report, this is now fixed on master
