### ISSUE TITLE
bug: can't regenerate after C update

### ISSUE THREAD

**Issue by ObserverOfTime** [tree-sitter/tree-sitter-cpp#238]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c)

### Describe the bug

Generating the CPP parser after updating tree-sitter-c results in an error: 
```
Unresolved conflict for symbol sequence:

  'typedef'  primitive_type  •  'signed'  …

Possible interpretations:

  1:  'typedef'  (_type_specifier  primitive_type)  •  'signed'  …
  2:  'typedef'  (sized_type_specifier  primitive_type  •  sized_type_specifier_repeat1)

Possible resolutions:

  1:  Specify a higher precedence in `sized_type_specifier` than in the other rules.
  2:  Specify a higher precedence in `_type_specifier` than in the other rules.
  3:  Specify a left or right associativity in `_type_specifier`
  4:  Add a conflict for these rules: `_type_specifier`, `sized_type_specifier`
```
Adding the conflict to the grammar requires adding even more conflicts, only for the tests to fail.

### Steps To Reproduce/Bad Parse Tree

```bash
git clone https://github.com/tree-sitter/tree-sitter-cpp
cd tree-sitter-cpp
npm install
tree-sitter generate
```

### Expected Behavior/Parse Tree

There should not be any unresolved conflicts.

**Comment by amaanq** [comment]
Fixed on master, that wasn't pleasant :laughing:
