### ISSUE TITLE
bug: raw string literal eats translation unit under certain error scenarios

### ISSUE THREAD

**Issue by cdacamar** [tree-sitter/tree-sitter-cpp#245]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Describe the bug

This is actually sort of two bugs in one:

1. The qualified base access expression is not recognized by the grammar, e.g. `this->Base::f()`
2. When an error happens under certain productions, the grammar will attach a `raw_string_delimiter` as a recovery token (almost always wrong) and continue parsing the rest of the translation unit (TU).  When this happens and a real raw string literal is encountered, the parser will eat the entire rest of the translation unit trying to search for the corresponding synthesized `raw_string_delimiter` token.

### Steps To Reproduce/Bad Parse Tree

1. Open tree-sitter playground in C++ mode.
2. Use the TU provided below.
3. Observe that `raw_string_content` encompasses the entire rest of the TU.

```
translation_unit [0, 0] - [4, 0]
  ERROR [0, 0] - [4, 0]
    type: primitive_type [0, 0] - [0, 4]
    function_declarator [0, 5] - [0, 8]
      declarator: identifier [0, 5] - [0, 6]
      parameters: parameter_list [0, 6] - [0, 8]
    expression_statement [1, 4] - [1, 20]
      field_expression [1, 4] - [1, 14]
        argument: this [1, 4] - [1, 8]
        field: field_identifier [1, 10] - [1, 14]
      ERROR [1, 14] - [1, 19]
        raw_string_delimiter [1, 15] - [1, 17]
    type_qualifier [2, 4] - [2, 9]
    type: primitive_type [2, 10] - [2, 14]
    pointer_declarator [2, 14] - [2, 17]
      declarator: identifier [2, 16] - [2, 17]
    raw_string_content [2, 23] - [4, 0]
```

### Expected Behavior/Parse Tree

1. Parse the qualified base access correctly.
2. Try not to use raw string literal delimiters as recovery tokens.

### Repro

```cpp
void f() {
    this->Base::f();
    const char* s = R"(s)";
}
```

**Comment by amaanq** [comment]
Yeah we shouldn't be using raw string delimiter in error recovery, that's a good catch and has an easy fix. The actual issue, maybe not so much.
