### ISSUE TITLE
C++11 template type alias declarations

### ISSUE THREAD

**Issue by Aerijo** [tree-sitter/tree-sitter-cpp#25]
Not sure what these are, I just got told that there's an error in the parse tree. The code itself [is from `cquery`](https://github.com/cquery-project/cquery/blob/master/src/clang_cursor.h#L94), so it should be valid.

```
#pragma once

class ClangCursor {
 public:
  template <typename TClientData>
  using Visitor = VisitResult (*)(ClangCursor cursor,
                                  ClangCursor parent,
                                  TClientData* client_data);
};
```
The errors are in `#pragma once` (which I understand is not standardised, but is widely used), and `VisitResult (*)`. Looks like the template is the cause?

**Comment by maxbrunsfeld** [comment]
The `#pragma once` parses ok, as a generic preprocesser call.

I hadn't heard of that templated `using` syntax. I think it's documented here:
https://en.cppreference.com/w/cpp/language/type_alias.
