### ISSUE TITLE
feature: Python Bindings

### ISSUE THREAD

**Issue by Rot127** [tree-sitter/tree-sitter-cpp#250]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

[py-tree-sitter](https://github.com/tree-sitter/py-tree-sitter/) marked their method to build tree-sitter libraries and [seems to allow](https://github.com/tree-sitter/py-tree-sitter/blob/master/README.md#build-from-source) only languages with Python bindings in `v0.22.0`.

### Describe the solution you'd like

Implement Python bindings to `py-tree-sitter`

### Describe alternatives you've considered

Stick to version `<0.22.0` for the Python API or use another one. Though I am not aware of any which allows building `tree-sitter-cpp` on my own.

**Comment by amaanq** [comment]
They're available now at https://pypi.org/project/tree-sitter-cpp
