### ISSUE TITLE
bug: pure virtual destructor declaration

### ISSUE THREAD

**Issue by MarcelRobitaille** [tree-sitter/tree-sitter-cpp#251]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.20.8

### Describe the bug

Virtual functions with `= 0;` are sometimes not parsed correctly. It seems to occur when they do not take any arguments.

### Steps To Reproduce/Bad Parse Tree
```scheme
(translation_unit [0, 0] - [4, 0]
  (class_specifier [0, 0] - [3, 1]
    name: (type_identifier [0, 6] - [0, 11])
    body: (field_declaration_list [1, 0] - [3, 1]
      (declaration [2, 3] - [2, 23]
        (virtual [2, 3] - [2, 10])
        declarator: (function_declarator [2, 11] - [2, 18]
          declarator: (identifier [2, 11] - [2, 16])
          parameters: (parameter_list [2, 16] - [2, 18]))
        (ERROR [2, 19] - [2, 22]
          (number_literal [2, 21] - [2, 22]))))))
test.cpp        0 ms    (ERROR [2, 19] - [2, 22])
```
### Expected Behavior/Parse Tree
```scheme
(translation_unit [0, 0] - [4, 0]
  (class_specifier [0, 0] - [3, 1]
    name: (type_identifier [0, 6] - [0, 11])
    body: (field_declaration_list [1, 0] - [3, 1]
      (field_declaration [2, 3] - [2, 27]
        (virtual [2, 3] - [2, 10])
        type: (type_identifier [2, 11] - [2, 16])
        declarator: (parenthesized_declarator [2, 16] - [2, 22]
          (field_identifier [2, 17] - [2, 21]))
        default_value: (number_literal [2, 25] - [2, 26])))))
```
### Repro

```cpp
class Class
{
   virtual ~Class() = 0;
};
```
However, if I add `void` like this, I get the expected result:
```cpp
class Class
{
   virtual ~Class(void) = 0;
};
```

**Comment by jdrouhard** [comment]
This is invalid c++

**Comment by MarcelRobitaille** [comment]
Ok, it's not valid for a constructor. My actual case was a destructor. I've updated the description.
