### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Acture** [tree-sitter/tree-sitter-cpp#255]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Describe the bug

The following code is parsed without error:

    ListNode* sortList(ListNode* head) {
        ListNode* merge(ListNode* head1, ListNode* head2) {
            ListNode* dummyHead = new ListNode(0);
            ListNode* temp = dummyHead;
            ListNode* temp1 = head1;
            ListNode* temp2 = head2;
            while (temp1 && temp2) {
                if (temp1->val <= temp2->val) {
                    temp->next = temp1;
                    temp1 = temp1->next;
                } else {
                    temp->next = temp2;
                    temp2 = temp2->next;
                }
                temp = temp->next;
            }
            if (temp1) {
                temp->next = temp1;
            } else if (temp2) {
                temp->next = temp2;
            }
            return dummyHead->next;
        }
        
        if (!head) {
            return head;
        }
        
        int length = 0;
        ListNode* node = head;
        while (node) {
            length++;
            node = node->next;
        }
        
        ListNode* dummyHead = new ListNode(0, head);
        int subLength = 1;
        while (subLength < length) {
            ListNode* prev = dummyHead;
            ListNode* curr = dummyHead->next;
            while (curr) {
                ListNode* head1 = curr;
                for (int i = 1; i < subLength; i++) {
                    if (curr->next) {
                        curr = curr->next;
                    } else {
                        break;
                    }
                }
                ListNode* head2 = curr->next;
                curr->next = NULL;
                curr = head2;
                for (int i = 1; i < subLength; i++) {
                    if (curr && curr->next) {
                        curr = curr->next;
                    } else {
                        break;
                    }
                }
                
                ListNode* succ = NULL;
                if (curr) {
                    succ = curr->next;
                    curr->next = NULL;
                }
                
                ListNode* merged = merge(head1, head2);
                prev->next = merged;
                while (prev->next) {
                    prev = prev->next;
                }
                curr = succ;
            }
            subLength <<= 1;
        }
        
        return dummyHead->next;
    }
};

### Steps To Reproduce/Bad Parse Tree

parse the previous code in treesitter playground.

### Expected Behavior/Parse Tree

The secondary function definition should be illegal.

### Repro

```cpp
// Example code that causes the issue
void foo() {
  // Code that fails to parse, or causes an error
}
```

**Comment by amaanq** [comment]
tree-sitter is generally permissive about parsing, and this is *syntactically* fine, but it won't compile. restricting this might make the parser state count worse, however, if it's negligible a pr would be welcome then
