### ISSUE TITLE
bug: 0.21.0: missing symbol static_assert

### ISSUE THREAD

**Issue by 0-wiz-0** [tree-sitter/tree-sitter-cpp#256]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

n/a

### Describe the bug

When building tree-sitter-cpp 0.21.0 from pkgsrc on NetBSD/amd64 in the same as building 0.20.5, I have a problem loading the shared object:
```
/usr/pkg/lib/libtree-sitter-cpp.so: Undefined PLT symbol "static_assert" (symnum = 15)
```
And indeed, `nm` confirms that:
```
00000000004a0ce0 d language.0
                 U memcpy
                 U static_assert
```
I tried building 0.20.5 again in the same exact way, and here 'static_assert' doesn't appear in the so file at all.

I don't know how to fix this, any ideas?

### Steps To Reproduce/Bad Parse Tree

n/a

### Expected Behavior/Parse Tree

n/a

### Repro

```cpp
n/a
```

**Comment by ObserverOfTime** [comment]
You need to set `-std=c11`. The `Makefile` does that for you.

**Comment by 0-wiz-0** [comment]
Thank you! Using c11 for building fixed the problem for me.
