### ISSUE TITLE
bug: Treesitter does not recognize a template function that is a member of an instance of a class, where the type is specified when calling

### ISSUE THREAD

**Issue by ConnorSweeneyDev** [tree-sitter/tree-sitter-cpp#262]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Describe the bug

When calling a template function, if it is a member of an instance of a class AND you specify the <type> when calling, running :Inspect on the function returns a no items found message, and the function is not highlighted.

### Steps To Reproduce/Bad Parse Tree

Write a class with a public template function, extern an instance of the class, call that function from the extern instance and specify a type, the function will not be highlighted.

### Expected Behavior/Parse Tree

The function should be recognized by treesitter.

### Repro

```cpp
class foo {
    public:
        template <typename Type> void function(int argument) {
            // Do something
        }
};
extern foo instance;

int main() {
    instance.function<int>(5);
    return 0;
}
```

**Comment by amaanq** [comment]
highlighting is not performed here (unless done so w/ the cli).
