### ISSUE TITLE
bug: [BUG]When parsing template functions that contain function pointers, parsing will fail.

### ISSUE THREAD

**Issue by songhtdo** [tree-sitter/tree-sitter-cpp#268]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Describe the bug

typedef QtPrivate::FunPointer<void (SuSurfaceNav::*)(void)const > fnNuj;

### Steps To Reproduce/Bad Parse Tree

![image](https://github.com/tree-sitter/tree-sitter-cpp/assets/22132121/7bdff843-0f68-407b-8761-0806cc95ed2a)

### Expected Behavior/Parse Tree

Expect the parsing to be correct.

### Repro

```cpp
// Example code that causes the issue
void foo() {
  // Code that fails to parse, or causes an error
}
```

**Comment by touzeauv** [comment]
I looked at the issue but I could not solve the problem so far.
Here are some others examples that I think are related and fails or are parsed incorrectly if someone wants to give it a try:
```cpp
// Parsed as a function call
void (A::f*) ();
// Note that void (A::f*) (void) is correctly parsed as a method pointer declaration
```

```cpp
// Regular function pointer suffer the same problem
void (*f) (); // Parsed as function call
// void (*f)(void) is correctly parsed as function pointer declaration
```

```cpp
// Inside a template parameter, the name should be optional, but this fails
B<void (A::*) ()> b;
```
