### ISSUE TITLE
bug: Emacs c++-ts-mode failing with "Node type error at" 575

### ISSUE THREAD

**Issue by breadsander** [tree-sitter/tree-sitter-cpp#271]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Describe the bug

Someone else is running into this as well in https://www.reddit.com/r/emacs/comments/1d7tx5s/emacs_upgrade_problems/

I've been working on getting treesitter up and running for Emacs and I am using the latest tree-sitter-cpp grammars (pulled today). When I attempt to enable it in Emacs I get the following query error:

Error during redisplay: (jit-lock-function 2785) signaled (treesit-query-error "Node type error at" 575 "[\"_Atomic\" \"break\" \"case\" \"const\" \"continue\" \"default\" \"do\" \"else\" \"enum\" \"extern\" \"for\" \"goto\" \"if\" \"inline\" \"register\" \"restrict\" \"return\" \"sizeof\" \"static\" \"struct\" \"switch\" \"typedef\" \"union\" \"volatile\" \"while\" \"and\" \"and_eq\" \"bitand\" \"bitor\" \"catch\" \"class\" \"co_await\" \"co_return\" \"co_yield\" \"compl\" \"concept\" \"consteval\" \"constexpr\" \"constinit\" \"decltype\" \"delete\" \"explicit\" \"final\" \"friend\" \"mutable\" \"namespace\" \"new\" \"noexcept\" \"not\" \"not_eq\" \"operator\" \"or\" \"or_eq\" \"override\" \"private\" \"protected\" \"public\" \"requires\" \"template\" \"throw\" \"try\" \"typename\" \"using\" \"virtual\" \"xor\" \"xor_eq\"] @font-lock-keyword-face (auto) @font-lock-keyword-face (this) @font-lock-keyword-face" "Debug the query with `treesit-query-validate'")

Admittedly, I am not sure whether this is an Emacs tree-sitter package issue, or an issue with the grammar itself. So, my apologies if this is not the right place to file an issue.

All other tree-sitter grammer **are working correctly** in my Emacs configuration-- just not this one.

I am going to see if syncing to an earlier version might fix this.

### Steps To Reproduce/Bad Parse Tree

1. Compile emacs with tree-sitter capabilities
2. Acquire the 'tree-sitter' package
3. Get the head-of-line C++ tree-sitter grammar
4. Compile it and install it via 'treesit-install-language-grammar'
5. Go to C++ file and enable c++-ts-mode

### Expected Behavior/Parse Tree

Symbol highlighting to be enabled.

### Additional notes

I have got the head-of-line of tree-sitter and recompiled Emacs with that. It is still failing to function properly.

**Comment by breadsander** [comment]
Alright, I think I have a root cause-- but I'm not going to know how to fix any of this.

Node type error at 575 is referencing the 'virtual' node-type in the query. 

Everything appears to work if I revert the repo to:

commit 72fd00128f1c38319670cbf4bcedbba0dc849d96 (HEAD, tag: v0.22.0)
Date:   Sun Apr 14 21:38:58 2024 -0400

So, I can expect that perhaps https://github.com/tree-sitter/tree-sitter-cpp/commit/c51ffe9d7b67aa9500db01c26d8c075cfe032d0f has caused this issue.

**Comment by scturtle** [comment]
> Node type error at 575 is referencing the 'virtual' node-type in the query.

Hi, how do you debug the query in emacs? I have no idea before.

I just found that after deleting the `virtual` keyword in function `c-ts-mode--keywords` in `c-ts-mode.el`, all font lock faces are back again.

**Comment by amaanq** [comment]
emacs should not be blindly updating parsers without ensuring that the queries used still work.

**Comment by casouri** [comment]
Tree-sitter grammars should really be versioned but that's a discussion for another day. 

So the virtual keyword is not an anonymous node anymore? But isn't it always `virtual` in the source?
