### ISSUE TITLE
bug: no syntax highlighting in C++ code when trying to use treesit and c++-ts-mode

### ISSUE THREAD

**Issue by zzachimed** [tree-sitter/tree-sitter-cpp#274]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Describe the bug

I'm trying to enable treesitter in Emacs 29 (GNU Emacs 29.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.41, cairo version 1.18.0)  Ubuntu 24.04 LTS  Linux 6.8.0-38-generic). I get the following error in *Messages* and no syntax highlighting in C++ code;

```
Error during redisplay: (jit-lock-function 1) signaled (treesit-query-error "Node type error at" 575 "[\"_Atomic\" \"break\" \"case\" \"const\" \"continue\" \"default\" \"do\" \"else\" \"enum\" \"extern\" \"for\" \"goto\" \"if\" \"inline\" \"register\" \"restrict\" \"return\" \"sizeof\" \"static\" \"struct\" \"switch\" \"typedef\" \"union\" \"volatile\" \"while\" \"and\" \"and_eq\" \"bitand\" \"bitor\" \"catch\" \"class\" \"co_await\" \"co_return\" \"co_yield\" \"compl\" \"concept\" \"consteval\" \"constexpr\" \"constinit\" \"decltype\" \"delete\" \"explicit\" \"final\" \"friend\" \"mutable\" \"namespace\" \"new\" \"noexcept\" \"not\" \"not_eq\" \"operator\" \"or\" \"or_eq\" \"override\" \"private\" \"protected\" \"public\" \"requires\" \"template\" \"throw\" \"try\" \"typename\" \"using\" \"virtual\" \"xor\" \"xor_eq\"] @font-lock-keyword-face (auto) @font-lock-keyword-face (this) @font-lock-keyword-face" "Debug the query with `treesit-query-validate'")
```

### Steps To Reproduce/Bad Parse Tree

1 M-x package-vc-install RET https://github.com/renzmann/treesit-auto.git
2 add this in emacs init.el
```
 (use-package treesit-auto
  :custom
  (treesit-auto-install 'prompt)
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode))
(setq treesit-font-lock-level 4)
```
3  M-x treesit-auto-install-all

### Expected Behavior/Parse Tree

no error report and highlight c++ syntax correct

### Repro

```cpp
#include <iostream>
#include <vector>

int main()
{
 // std::atomic<int> b(1);
 // b.store(123);
 std::vector<int> zz;
 zz.push_back(123);
 std::cout<<zz.front();
}
```

**Comment by zzachimed** [comment]
![Screenshot from 2024-07-11 22-26-43](https://github.com/tree-sitter/tree-sitter-cpp/assets/98315055/5a60d27b-5989-4592-9e3d-9dd44e3fd6c6)

**Comment by amaanq** [comment]
this is an issue with Emacs, not us, we cannot help you here
