### ISSUE TITLE
bug: Macro is not expanded

### ISSUE THREAD

**Issue by learn-more** [tree-sitter/tree-sitter-cpp#276]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Describe the bug

Macro's are not expanded at all, even when it _should_ (probably?) be possible.

### Steps To Reproduce/Bad Parse Tree

```
#define LOG(x, ...) LOG_FUNCTION(logging::base, "LOG", x, __VA_ARGS__)
```
This results in:
```
(translation_unit
	(preproc_function_def
		name: (identifier)
		parameters: (preproc_params (identifier))
		value: (preproc_arg)))
```
Where `preproc_arg` is:
```
LOG_FUNCTION(logging::base, "LOG", x, __VA_ARGS__)
```

### Expected Behavior/Parse Tree

I expected some more decomposition in the `preproc_arg`

### Repro

Code used to generate the output:
```py
    parser = Parser(CPP_LANGUAGE)

    tree = parser.parse(b"""
#define LOG(x, ...) LOG_FUNCTION(logging::base, "LOG", x, __VA_ARGS__)
"""
    )

    print(tree.root_node)
    query = CPP_LANGUAGE.query("(preproc_params) @params")
    node = query.matches(tree.root_node)[0][1]['params']
    print(f'{node.type=}, {node.text=}')
    
    query = CPP_LANGUAGE.query("(preproc_arg) @args")
    node = query.matches(tree.root_node)[0][1]['args']
    print(f'{node.type=}, {node.text=}')
```

**Comment by amaanq** [comment]
the syntax for macros is extremely loosely defined - attempting to parse the preproc arg makes no sense. however, you can **inject** the parser in a preproc_arg node to see if that parses fine (nvim-treesitter does this, doesn't always work out though) and then "merge" the two trees

**Comment by learn-more** [comment]
> the syntax for macros is extremely loosely defined - attempting to parse the preproc arg makes no sense. however, you can **inject** the parser in a preproc_arg node to see if that parses fine (nvim-treesitter does this, doesn't always work out though) and then "merge" the two trees

Thanks for the reply!

What I could find about injections only specifies how to define them: https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection

After that, would I need to re-generate `src/parser.c` ?

**Comment by amaanq** [comment]
So injections are implementation-dependent. Typically, you would query for the nodes that are meant to be injected, in this case, a `preproc_arg`, and then you would parse *this* node's text alone using the same parser again, to get more information out of that beyond it being a `preproc_arg`. But note that this won't always work, especially in funkier macros.

**Comment by learn-more** [comment]
> So injections are implementation-dependent. Typically, you would query for the nodes that are meant to be injected, in this case, a `preproc_arg`, and then you would parse *this* node's text alone using the same parser again, to get more information out of that beyond it being a `preproc_arg`. But note that this won't always work, especially in funkier macros. 

Thanks, I'll try this.
