### ISSUE TITLE
Errors detected for valid C

### ISSUE THREAD

**Issue by genotrance** [tree-sitter/tree-sitter-cpp#28]
From the ImageMagick codebase - [image-view.h](https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/image-view.h#L28):

```c++
typedef MagickBooleanType
  (*DuplexTransferImageViewMethod)(const ImageView *,const ImageView *,
    ImageView *,const ssize_t,const int,void *),
  (*GetImageViewMethod)(const ImageView *,const ssize_t,const int,void *),
  (*SetImageViewMethod)(ImageView *,const ssize_t,const int,void *),
  (*TransferImageViewMethod)(const ImageView *,ImageView *,const ssize_t,
    const int,void *),
(*UpdateImageViewMethod)(ImageView *,const ssize_t,const int,void *);
```

Multi-line function declaration with same return value, separated by commas - tree-sitter errors on the `,`.

AST output is [here](http://ix.io/1y3O/Lisp). See line 65.

**Comment by maxbrunsfeld** [comment]
Oh, I didn't know you could define multiple types in a single `typedef` statement. Should be an easy fix. Thanks for the report!

**Comment by genotrance** [comment]
These aren't types, you are defining multiple functions that return the same type. This is similar to [MagicWand.h](https://github.com/ImageMagick/ImageMagick/blob/master/MagickWand/MagickWand.h#L111) which tree-sitter supports just fine.

**Comment by maxbrunsfeld** [comment]
No, this is typedef statement. It defines types of functions. `DuplexTransferImageViewMethod` is a function *type*. So is `UpdateImageViewMethod`.

`DuplexTransferImageViewMethod` itself is not a function.

**Comment by genotrance** [comment]
Thanks for explaining! Hope it gets fixed soon - I have 10 symbols I cannot parse due this limitation.

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/tree-sitter/tree-sitter-c/commit/5a25ac29838204ab1045aa454bbd7dba38b61aa0.
