### ISSUE TITLE
backslash in comment leads to an error

### ISSUE THREAD

**Issue by calixteman** [tree-sitter/tree-sitter-cpp#36]
For example with
```c
int foo() {
    // a backslash \t ...
    return 0;
}
```
I got an error because of the "\\" in the comment.
It's probably a consequence of https://github.com/tree-sitter/tree-sitter-c/commit/1358e07759742d18269dc516564e2a00ab7248ef.

**Comment by marehr** [comment]
If this is fixed, it should also resolve atom/language-c#327

**Comment by Ben3eeE** [comment]
This should be fixed by https://github.com/tree-sitter/tree-sitter-c/pull/17. Let me know if I am misunderstanding something.
