### ISSUE TITLE
Constexpr Incorrect Highlighting

### ISSUE THREAD

**Issue by nick-prat** [tree-sitter/tree-sitter-cpp#4]
Constexpr doesn't seem to follow the same rules as other type specifiers such as static and cost

![constexpr_treesitter](https://user-images.githubusercontent.com/19151224/39906508-0420eee8-5498-11e8-85f0-f7794ac8e85d.png)

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/tree-sitter/tree-sitter-cpp/commit/64ac620f5d988938ca605e028616b15293bf4b2a. Thanks for the report!
