### ISSUE TITLE
Struct with __attribute__

### ISSUE THREAD

**Issue by EvgeniyPeshkov** [tree-sitter/tree-sitter-cpp#47]
Structures with attributes are parsed incorrectly. For example:
```
struct __attribute__((packed)) struct1_t {
    static constexpr int A = 1;
    static constexpr int B = 2;
};
```
It seems to me, that they are taken for `function_definition` somehow.
This will help to resolve [this issue](https://github.com/EvgeniyPeshkov/syntax-highlighter/issues/21).
Thank you very much.

**Comment by Arcanemagus** [comment]
What version of `tree-sitter-cpp` are you using? This looks like it should have been fixed by https://github.com/tree-sitter/tree-sitter-c/pull/19, which would be included in `tree-sitter-cpp@0.15.0`.

**Comment by Arcanemagus** [comment]
Nevermind, just checked your linked repository and it appears you are already on that version.

**Comment by EvgeniyPeshkov** [comment]
I use the latest version 0.15.0.
It seems that `__attribute__` was fixed for function declarations, but not structs.
