### ISSUE TITLE
Template Class Constructors parsed incorrectly

### ISSUE THREAD

**Issue by rsese** [tree-sitter/tree-sitter-cpp#50]
*@rsese - copied over @BeefaloKing's report from https://github.com/atom/language-c/issues/332*

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Both the name and initializer list of template class constructors have incorrect syntax highlighting when defined outside the class declaration.
![image](https://user-images.githubusercontent.com/9630438/59861089-69461700-933d-11e9-9809-4300e55b13c9.png)
Edit: Added clarity in screenshot

*Edit by @rsese - copying over a [comment](https://github.com/atom/language-c/issues/332#issuecomment-504070329)*

> The foo() and data(nullptr) on line 17. These should match the highlighting for the constructor bar() on line 20.
>
> Additionally, if foo() were not a constructor, and had a return type, it would be highlighted correctly. (e.g. template<typename T> int foo<T>::foobar())

### Steps to Reproduce

1. Define a constructor for a template class outside the class declaration
```
template<typename T> class foo
{
public:
	foo();
private:
	T *data;
};

class bar
{
public:
	bar();
private:
	int *data;
};

template<typename T> foo<T>::foo() : data(nullptr)
{}

bar::bar() : data(nullptr)
{}
```

### Versions

Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Possible Related Issues

https://github.com/atom/language-c/issues/90

**Comment by BeefaloKing** [comment]
(Presumably) this same issue also happens when a constructor uses a function try block.
```
class bar
{
public:
	bar();
private:
	int *data;
};

bar::bar() try : data(nullptr)
{
    //Do Something
}
catch (...)
{
    //Do Something
}
```
