### ISSUE TITLE
No distinction between line/block comments

### ISSUE THREAD

**Issue by savetheclocktower** [tree-sitter/tree-sitter-cpp#52]
There appears to be one type of comment node, and it's called `comment`. Both line comments and block comments are assigned to this node type. As a result, the grammar in atom/language-c can't distinguish between the two types and scopes both as `comment` rather than `comment.line` or `comment.block`.

This means that line comments can't be styled differently from block comments. It also means that a package like [DocBlockr](https://atom.io/packages/docblockr) can't function properly because it relies on the scope name to tell it how to behave within different types of comments.

I'm not a C++ expert, to put it mildly; so if there's a reason for this that I'm unfamiliar with, please let me know.

**Comment by amaanq** [comment]
You can use queryes w/ a match predicate to filter these

**Comment by savetheclocktower** [comment]
Heh, I forgot I even opened this ticket. Atom's mapping from nodes to scope names wasn't yet doing any matching against node content, and the query engine wasn't in place yet. Blast from the past.

**Comment by amaanq** [comment]
wow, I wasn't even around then :sweat_smile:
