### ISSUE TITLE
Const pointer to const

### ISSUE THREAD

**Issue by nick-prat** [tree-sitter/tree-sitter-cpp#7]
The second const in a const pointer to const declaration isn't highlighted

![const_pointer_to_const](https://user-images.githubusercontent.com/19151224/42523375-93d1fa14-843b-11e8-9873-0bdf2f7d1e29.png)

**Comment by maxbrunsfeld** [comment]
Thanks for the report; I forgot to implement that! This'll be fixed in the next Atom release.
