### ISSUE TITLE
The C++ grammar is ambiguous

### ISSUE THREAD

**Issue by HighCommander4** [tree-sitter/tree-sitter-cpp#74]
I just come across the [Strange Loop talk](https://www.youtube.com/watch?v=Jes3bD6P0To) about tree-sitter, which claimed that tree-sitter aims to enable syntax highlighting that both:

  1. does not require building a full semantic model of the code (the way, say, an LSP language server would); and
  2. highlights different language elements differently, e.g. types differently from variables

It seems to me that these two goals are in fundamental conflict for a language with an ambiguous grammar such as C++.

To take the classic example: in a statement context, the following statement in C++:

```
a * b;
```

is ambiguous between an expression-statement which multiplies the two variables `a` and `b`, and a declaration-statement which declares a variable `b` of type pointer-to`a`. The answer depends on how `a` is previously declared: as a variable, or as a type (and note the declaration could occur in an included header file).

A quick check in the [tree-sitter playground](http://tree-sitter.github.io/tree-sitter/playground) suggests that tree-sitter is always parsing this as a declaration-statement. For example, given the input code:

```
int a, b;
void foo() {
  a * b;
}
```

the resulting syntax tree is:

```
translation_unit [0, 0] - [4, 0])
  declaration [0, 0] - [0, 9])
    type: primitive_type [0, 0] - [0, 3])
    declarator: identifier [0, 4] - [0, 5])
    declarator: identifier [0, 7] - [0, 8])
  function_definition [1, 0] - [3, 1])
    type: primitive_type [1, 0] - [1, 4])
    declarator: function_declarator [1, 5] - [1, 10])
      declarator: identifier [1, 5] - [1, 8])
      parameters: parameter_list [1, 8] - [1, 10])
    body: compound_statement [1, 11] - [3, 1])
      declaration [2, 2] - [2, 8])
        type: type_identifier [2, 2] - [2, 3])
        declarator: pointer_declarator [2, 4] - [2, 7])
          declarator: identifier [2, 6] - [2, 7])
```

Notably, syntax highlighting built on top of this would incorrectly color the `a` token in `a * b` as a type, rather than as a variable.

How does tree-sitter plan to deal with such ambiguities?

**Comment by HighCommander4** [comment]
Note that this is just one of many places in the C++ grammar that's ambiguous. Another very common example is template arguments:

```
template <typename A, int B>
struct C {};

struct X {};
int Y;
C<X, Y> c;
```

Here, tree-sitter parses both the `X` and the `Y` in `C<X, Y>` as types when in fact `Y` is a variable.

**Comment by maxbrunsfeld** [comment]
Yup, these are the intended behaviors; there are already specific tests for both of these cases in the test suite.

Tree-sitter is designed to be a fast, zero-configuration, parsing system that works across many programming languages. It's not a C++ code analysis engine .  that would require compiler flags to be provided as inputs, and wouldn't work well for arbitrary unknown C++ code.
