### ISSUE TITLE
value field of declaration node is required in node-types.json but does not exist in parse tree

### ISSUE THREAD

**Issue by 2yz** [tree-sitter/tree-sitter-cpp#83]
It is said that value field of declaration node is required in node-types.json. The following code is related part of node-types.json.

```
  {
    "type": "declaration",
    "named": true,
    "fields": {
      .....
      "value": {
        "multiple": false,
        "required": true,
        "types": [
          {
            "type": "_expression",
            "named": true
          },
          {
            "type": "initializer_list",
            "named": true
          }
        ]
      },
      .....
    },
```

However, value field of declaration node does not exist in the parse tree generated by tree sitter. The parse tree of source code `int func();` is,

```
declaration:
   children: [ 
     primitive_tive,
     function_declarator,
    ;
  ]
  ...
```

The field name of `primitive_tive` child node is `type` and field name of `function_declarator ` child node is `declarator`. However, there is no child node with `value` field name.

**Comment by maxbrunsfeld** [comment]
You're right, thanks for the report. This is a bug in the way `node-types.json` is being generated. I will try to look into this in the next couple of weeks.

**Comment by CamilleTeruel** [comment]
@maxbrunsfeld 
Looking at the [declaration rule](https://github.com/tree-sitter/tree-sitter-cpp/blob/72348197be713c5bb43307200dde52a5a62cc0b6/grammar.js#L198) of the grammar, the fields `value` and `default_value` should not be there. AFAICT, it should have exactly the same fields than the [C version](https://github.com/tree-sitter/tree-sitter-c/blob/88592f162e218e3d0de28f1e5d1835e6ef2c57b6/src/node-types.json#L968).

Looking at file history of `node-types.json` the commits that introduced the `value` and `default_value` fields in declaration node type are f2e0cd5e and 95703675 respectively.
The lines that expose the underlying bug seem to be:

https://github.com/tree-sitter/tree-sitter-cpp/blob/72348197be713c5bb43307200dde52a5a62cc0b6/grammar.js#L663

https://github.com/tree-sitter/tree-sitter-cpp/blob/72348197be713c5bb43307200dde52a5a62cc0b6/grammar.js#L354

I regenerated to make sure `node-type.json` was up to date with latest generation code (tree-sitter-cli v0.16.5), but it is. However, `default_value` is not generated using tree-sitter-cli v0.15.13, so it might be two different bugs, one of which is introduced in tree-sitter-cli v0.15.14.

HTH

**Comment by maxbrunsfeld** [comment]
Ok, a couple of answers:

1. The `default_value` field was already correct. The `operator_cast_declaration` has an optional `default_value` field, and as @CamilleTeruel points out, the `operator_cast_declaration` is *aliased* as a `declaration` in the grammar.

    This means that at runtime, a syntax node of type `declaration` may have been generated by the `operator_cast_declaration` rule, so it can optionally have a `default_value` field.

2. The `value` field was **not** correct. It should indeed be *present* for a similar reason as `default_value`, but it should have `required` set to `false`. The `required` flag was being computed incorrectly due to a bug in Tree-sitter, which is now fixed in commit https://github.com/tree-sitter/tree-sitter/commit/9d182bb0785f158ba5b6ab14df8fae0eff8aa819. I am publishing a new release of the Tree-sitter CLI and then I will regenerate the node-types.

**Comment by maxbrunsfeld** [comment]
Also, just curious - are you folks able to share what you're using the `node-types.json` for? I'm curious what language you are using Tree-sitter from, and how well it is working to use the node types. We have only really used it from Haskell, and it took a bit of effort to get it to work nicely.

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/tree-sitter/tree-sitter-cpp/commit/20dc2e4301985c354bb91aa30723bb04ffe391c1

**Comment by CamilleTeruel** [comment]
Thanks for the fix @maxbrunsfeld, that was fast!

> This means that at runtime, a syntax node of type declaration may have been generated by the operator_cast_declaration rule, so it can optionally have a default_value field.

Oh I see, I was interpreting the aliasing feature the wrong way 😄 (`operator_cast_declaration` nodes with the same fields than `declaration` plus extra ones).

> Also, just curious - are you folks able to share what you're using the node-types.json for? I'm curious what language you are using Tree-sitter from, and how well it is working to use the node types. We have only really used it from Haskell, and it took a bit of effort to get it to work nicely.

Sure, we use tree-sitter from python. We use `node-type.json` to generate:
- a hierarchy of classes for each parse tree node type,
- a type-directed traversal of parse trees. It is then used to transform parse trees into language-agnostic ASTs via a term rewriting library. We use those ASTs to perform various analyses.

I guess it is somewhat similar to what `haskell-tree-sitter`/`semantic` are doing.
