### ISSUE TITLE
Support nested namespace definition

### ISSUE THREAD

**Issue by hashinclude** [tree-sitter/tree-sitter-cpp#86]
C++ 17 allows nested namespace definition - https://en.cppreference.com/w/cpp/language/namespace
However the parser doesn't understand this - 
<img width="1680" alt="Screen Shot 2020-08-13 at 4 54 42 AM" src="https://user-images.githubusercontent.com/1989695/90131509-1c7f8580-dd21-11ea-917b-eb87eeecc2f2.png">

**Comment by jdrouhard** [comment]
Fixed in #82
