### ISSUE TITLE
virtual functions error

### ISSUE THREAD

**Issue by kkoomen** [tree-sitter/tree-sitter-cpp#88]
#39 Should have added support for virtual functions, but when using npmjs.com/package/tree-sitter-cpp it doesn't work. I do get an error with parsing:

```javascript
const Parser = require('tree-sitter');
const CPP = require('tree-sitter-cpp');

const parser = new Parser();
parser.setLanguage(CPP);

const sourceCode = `
virtual void bar();
virtual void foo() {}
`;

const tree = parser.parse(sourceCode);
console.log(tree.rootNode.toString());
```

The above results in this tree (notice the `ERROR` keywords):

```
(translation_unit (ERROR (virtual_function_specifier) (ERROR (identifier)) (function_declarator declarator: (identifier) parameters: (parameter_list))) (expression_statement) (function_definition (virtual_function_specifier) (ERROR (identifier)) declarator: (function_declarator declarator: (identifier) parameters: (parameter_list)) body: (compound_statement)))
```

**Comment by jdrouhard** [comment]
Virtual function declarations/definitions are only valid in class scope, not global scope. If you place your virtual functions inside a `class {};` block, it parses correctly.

From cppreference:
> The virtual specifier specifies that a non-static member function is virtual and supports dynamic dispatch. It may only appear in the decl-specifier-seq of the initial declaration of a non-static member function (i.e., when it is declared in the class definition).

**Comment by kkoomen** [comment]
I confirm that works. Thanks.
