### ISSUE TITLE
Raw string literals?

### ISSUE THREAD

**Issue by sebastiansturm** [tree-sitter/tree-sitter-cpp#90]
After watching a related EmacsConf 2020 talk, I recently enabled emacs-tree-sitter and found that it generally provides excellent syntax highlighting, though surprisingly not for raw string literals. Adding `(raw_string_literal) @string` to cpp's highlights.scm superficially seems to fix that, but I assume there's a reason why raw string literals are not part of the default queries. Is raw string literal support planned, or is there some config parameter I should set to enjoy raw string highlighting?

**Comment by maxbrunsfeld** [comment]
I think it was probably an accident that they weren’t included in the highlight query. I don’t think there’s any other change that would need to be made.

**Comment by sebastiansturm** [comment]
alright, thanks!

**Comment by jdrouhard** [comment]
Fixed in #91
