### ISSUE TITLE
capture-api cannot handle "and" keyword correctly

### ISSUE THREAD

**Issue by dnns92** [tree-sitter/tree-sitter-cpp#94]
I use py-tree-sitter with the grammar *of this repository* to parse c++/c files. However I found that the "and" keyword leads to a weird behaviour. I'm not sure if I should post it here or at py-tree-sitter. Feel free to tell me.

See this code example:

```
void something() {
if (some_var and some_other_var == nullptr) {
    doSomething();
    }

}

void something2() {
if (some_var && some_other_var == nullptr) {
    doSomething();
    }

}
```

This should lead to something similar, as the "and" keyword basically is the "&&" operator. (IIRC)

However, when capturing the if-statements' content I get these returns:
```
file_captures[0][0].sexp()
'(condition_clause initializer: (declaration type: (type_identifier) declarator: (identifier) (MISSING ";")) value: (binary_expression left: (identifier) right: (nullptr)))'
file_captures[1][0].sexp()
'(condition_clause value: (binary_expression left: (identifier) right: (binary_expression left: (identifier) right: (nullptr))))'
```

So I think the "and" keyword is not handled properly, leading the tree-sitter to assume there is a missing ";" somewhere. Its not a type_identifier at all.

**Comment by bronikkk** [comment]
I can't see support for
https://en.wikipedia.org/wiki/C_alternative_tokens
in the grammar.

**Comment by azabiong** [comment]
Hi, thank you for this plugin.
I tried the following rules for the keywords (and, or, not) in the if-statement, and it seems to work.
I am using it as a temporally solution, but I'm not sure what the correct 'precedence' value.

**grammar.js**
```javascript
    _expression: ($, original) => choice(
      ...

      $.alternative_and_or,
      $.alternative_not,
    ),

    alternative_and_or: $ => prec.left(-1, seq(
      $._expression, $.operator_and_or, $._expression,
    )),

    alternative_not: $ => prec.right(seq(
      'not', $._expression,
    )),

    operator_and_or: $ => choice(
        'and', 'or',
    ),
```

**highlights.scm**
```query
    (operator_and_or) @operator

    "not" @operator
```
