### ISSUE TITLE
Fails to install on windows with node v15.x, npm v7.0.15

### ISSUE THREAD

**Issue by JackieJoo** [tree-sitter/tree-sitter-cpp#95]
The package is used as a dependency in module wIntrospector.
tree-sitter-cpp fails to install on node v15.11.0, npm v7.6.0
```
C:\hostedtoolcache\windows\node\15.11.0\x64\node.exe --version
v15.11.0
C:\windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\node\15.11.0\x64\npm.cmd --version"
7.6.0
C:\windows\system32\cmd.exe /d /s /c node-gyp -v
v7.1.2
```
Link to the log
https://github.com/Wandalen/wIntrospector/runs/2022230723?check_suite_focus=true#step:7:22

Can you please make tree-sitter-cpp correctly install and work on Windows on the last release of node - v15.x?
Thank you.

**Comment by amaanq** [comment]
Try again on master, this is quite old and I would like to assume it compiles fine now (especially w/ the scanner being in C), and since the log file 404's now I can't really check it out myself
